// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgJOelM8gaIANynO0wHzzOn5K_QZAHczY',
    appId: '1:1023671824478:web:37449c5c036c27ed4c84cf',
    messagingSenderId: '1023671824478',
    projectId: 'estudiapp-e1646',
    authDomain: 'estudiapp-e1646.firebaseapp.com',
    storageBucket: 'estudiapp-e1646.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7vTozGznqD94zPvpNig0HPlyWxNZv2o4',
    appId: '1:1023671824478:android:bd705bc82ab07efe4c84cf',
    messagingSenderId: '1023671824478',
    projectId: 'estudiapp-e1646',
    storageBucket: 'estudiapp-e1646.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDE_ZF-p3Fd-1whfzKG_hBgkGJtWZkddFI',
    appId: '1:1023671824478:ios:47008bef48fd2ed34c84cf',
    messagingSenderId: '1023671824478',
    projectId: 'estudiapp-e1646',
    storageBucket: 'estudiapp-e1646.firebasestorage.app',
    iosBundleId: 'com.example.appUniversitaria',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDE_ZF-p3Fd-1whfzKG_hBgkGJtWZkddFI',
    appId: '1:1023671824478:ios:47008bef48fd2ed34c84cf',
    messagingSenderId: '1023671824478',
    projectId: 'estudiapp-e1646',
    storageBucket: 'estudiapp-e1646.firebasestorage.app',
    iosBundleId: 'com.example.appUniversitaria',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDgJOelM8gaIANynO0wHzzOn5K_QZAHczY',
    appId: '1:1023671824478:web:39e9d64dcf5bae3b4c84cf',
    messagingSenderId: '1023671824478',
    projectId: 'estudiapp-e1646',
    authDomain: 'estudiapp-e1646.firebaseapp.com',
    storageBucket: 'estudiapp-e1646.firebasestorage.app',
  );
}
